

class AI_Languages:
    """
    This class defines the languages supported by the AI features in OpenShot.
    The LANGUAGES dictionary maps language names to their respective language codes.
    """
    def __init__(self):
        self.asr_languages = {
            "Auto-detect": "auto",
            "Afrikaans": "af",
            "Amharic": "am",
            "Arabic": "ar",
            "Assamese": "as",
            "Azerbaijani": "az",
            "Bashkir": "ba",
            "Belarusian": "be",
            "Bulgarian": "bg",
            "Bengali": "bn",
            "Tibetan": "bo",
            "Breton": "br",
            "Bosnian": "bs",
            "Catalan": "ca",
            "Czech": "cs",
            "Welsh": "cy",
            "Danish": "da",
            "German": "de",
            "Greek": "el",
            "English": "en",
            "Estonian": "et",
            "Basque": "eu",
            "Persian": "fa",
            "Finnish": "fi",
            "Faroese": "fo",
            "French": "fr",
            "Galician": "gl",
            "Gujarati": "gu",
            "Hausa": "ha",
            "Hawaiian": "haw",
            "Hebrew": "he",
            "Hindi": "hi",
            "Croatian": "hr",
            "Haitian Creole": "ht",
            "Hungarian": "hu",
            "Armenian": "hy",
            "Indonesian": "id",
            "Icelandic": "is",
            "Italian": "it",
            "Japanese": "ja",
            "Javanese": "jw",
            "Georgian": "ka",
            "Kazakh": "kk",
            "Khmer": "km",
            "Kannada": "kn",
            "Korean": "ko",
            "Latin": "la",
            "Luxembourgish": "lb",
            "Lingala": "ln",
            "Lao": "lo",
            "Lithuanian": "lt",
            "Latvian": "lv",
            "Malagasy": "mg",
            "Maori": "mi",
            "Macedonian": "mk",
            "Malayalam": "ml",
            "Mongolian": "mn",
            "Marathi": "mr",
            "Malay": "ms",
            "Maltese": "mt",
            "Burmese": "my",
            "Nepali": "ne",
            "Dutch": "nl",
            "Norwegian Nynorsk": "nn",
            "Norwegian": "no",
            "Occitan": "oc",
            "Punjabi": "pa",
            "Polish": "pl",
            "Pashto": "ps",
            "Portuguese": "pt",
            "Romanian": "ro",
            "Russian": "ru",
            "Sanskrit": "sa",
            "Sindhi": "sd",
            "Sinhala": "si",
            "Slovak": "sk",
            "Slovenian": "sl",
            "Shona": "sn",
            "Somali": "so",
            "Albanian": "sq",
            "Serbian": "sr",
            "Sundanese": "su",
            "Swedish": "sv",
            "Swahili": "sw",
            "Tamil": "ta",
            "Telugu": "te",
            "Tajik": "tg",
            "Thai": "th",
            "Turkmen": "tk",
            "Tagalog": "tl",
            "Turkish": "tr",
            "Tatar": "tt",
            "Ukrainian": "uk",
            "Urdu": "ur",
            "Uzbek": "uz",
            "Vietnamese": "vi",
            "Yiddish": "yi",
            "Yoruba": "yo",
            "Cantonese": "yue",
            "Chinese": "zh"
        }

        self.xtts_languages = {
            "English": "en",
            "Spanish": "es",
            "French": "fr",
            "German": "de", 
            "Italian": "it", 
            "Portuguese": "pt", 
            "Polish": "pl", 
            "Turkish": "tr", 
            "Russian": "ru", 
            "Dutch": "nl", 
            "Czech": "cs", 
            "Arabic": "ar", 
            "Chinese": "zh-cn", 
            "Japanese": "ja", 
            "Hungarian": "hu", 
            "Korean": "ko", 
            "Hindi": "hi"
        }      